### ISSUE TITLE
missing dependency declarations

### ISSUE THREAD

**Issue by kingaza** [VLOGroup/tensorflow-icg#3]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: 
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
source
- **TensorFlow version (use command below)**:
1.5
- **Python version**: 
3.6.4
- **Bazel version (if compiling from source)**:
0.11.1
- **GCC/Compiler version (if compiling from source)**:
gcc 5.4.0
- **CUDA/cuDNN version**:
CUDA 9.0, cuDNN 7.1
- **GPU model and memory**:
GTX1060 6G, RAM 16G 
- **Exact command to reproduce**:
build.sh

### Describe the problem
It looks that the reference to cuda include is missing. 
However, the problem exists even after adding cxx_builtin_include_directory: "/usr/local/cuda-9.0/include" within toolchain{} in the file tensorflow/third_party/gpus/crosstool/CROSSTOOL.nvcc.tpl

### Source code / logs
ERROR: /home/kingaza/Work/tensorflow-icg/tensorflow/contrib/icg/BUILD:17:1: undeclared inclusion(s) in rule '//tensorflow/contrib/icg:python/ops/_icg_ops_gpu':
this rule is missing dependency declarations for the following files included by 'tensorflow/contrib/icg/kernels/ffttools.cu.cc':
  '/home/kingaza/Work/tensorflow-icg/tensorflow/contrib/icg/ops/ffttools.h'

**Comment by khammernik** [comment]
Hi,
did you pull the latest commit a11ad61? It should be fixed there.

**Comment by kingaza** [comment]
hi, @khammernik ,
you are right, it is due to the old version. 
thx.
